FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

COPY backend/control-manager/target/control-manager-*.jar /app/control-manager.jar

ENV JAVA_OPTS=""
EXPOSE 8081

ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /app/control-manager.jar"]
