-- Flyway V3: 日志接收存储表

CREATE TABLE IF NOT EXISTS access_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ts DATETIME NOT NULL,
  request_id VARCHAR(128) NULL,
  user_id BIGINT NULL,
  username VARCHAR(64) NULL,
  proxy_name VARCHAR(64) NULL,
  inbound_id BIGINT NULL,
  client_ip VARCHAR(64) NULL,
  client_port INT NULL,
  src_geo_country VARCHAR(64) NULL,
  src_geo_city VARCHAR(64) NULL,
  original_target_host VARCHAR(255) NULL,
  original_target_ip VARCHAR(64) NULL,
  original_target_port INT NULL,
  rewrite_target_host VARCHAR(255) NULL,
  rewrite_target_port INT NULL,
  dst_geo_country VARCHAR(64) NULL,
  dst_geo_city VARCHAR(64) NULL,
  inbound_protocol_type VARCHAR(32) NULL,
  outbound_protocol_type VARCHAR(32) NULL,
  route_policy_name VARCHAR(64) NULL,
  route_policy_id BIGINT NULL,
  bytes_in BIGINT NULL,
  bytes_out BIGINT NULL,
  status INT NULL,
  error_code VARCHAR(64) NULL,
  error_msg VARCHAR(255) NULL,
  request_duration_ms BIGINT NULL,
  dns_duration_ms BIGINT NULL,
  connect_duration_ms BIGINT NULL,
  connect_target_duration_ms BIGINT NULL,
  received_at DATETIME NOT NULL,
  UNIQUE KEY uk_access_logs_request_id (request_id),
  INDEX idx_access_logs_ts (ts),
  INDEX idx_access_logs_user_inbound (user_id, inbound_id)
);

CREATE TABLE IF NOT EXISTS auth_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ts DATETIME NOT NULL,
  proxy_name VARCHAR(64) NULL,
  inbound_id BIGINT NULL,
  user_id BIGINT NULL,
  username VARCHAR(64) NULL,
  client_ip VARCHAR(64) NULL,
  client_port INT NULL,
  success TINYINT(1) NOT NULL,
  fail_reason VARCHAR(128) NULL,
  protocol VARCHAR(32) NULL,
  received_at DATETIME NOT NULL,
  INDEX idx_auth_logs_ts (ts),
  INDEX idx_auth_logs_user (user_id),
  INDEX idx_auth_logs_inbound (inbound_id)
);